version: 1
accounts:
- name: alice
  coins:
  - 200000000gold
- name: bob
  coins:
  - 100000000gold
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000gold
validators:
- name: alice
  bonded: 100000000gold
